version: '3.8'
services:
  auditor:
    build: .
    container_name: auditor
    ports:
      - "5000:5000"

  jogador:
    build: .
    container_name: jogador

  # docker compose up --scale jogador=3 para dois jogadores